In [1]:
import torch
# 所谓的rand 就是从uniform distrubution中创建tensor
x = torch.rand(5,3)
print(x)

tensor([[0.7413, 0.3485, 0.6980],
        [0.5960, 0.9047, 0.4491],
        [0.8232, 0.4518, 0.2927],
        [0.4480, 0.3712, 0.0387],
        [0.1377, 0.8414, 0.3841]])


In [2]:
import sys
print(sys.executable)
torch.cuda.is_available()

/usr/bin/python3


True

In [3]:
# empty 就会返回 当前内存的值， tf与pytorch的不同点在于tf形状一般要用框框起来，而torch都是直接接受未定长度的字符
x = torch.empty(5,3)
print(x)

tensor([[2.4556e-18, 1.9421e+31, 2.7491e+20],
        [6.1949e-04, 7.1856e+22, 4.3605e+27],
        [2.3329e-18, 1.9284e+31, 3.2314e-18],
        [3.2675e+21, 8.4569e+20, 6.5644e-07],
        [6.7200e-07, 2.6081e+20, 1.6892e-07]])


In [4]:
# rand 会返回零到一之间的数值
x = torch.rand(5, 3)
print(x)

tensor([[0.3317, 0.7661, 0.3896],
        [0.2991, 0.1369, 0.1923],
        [0.9069, 0.5091, 0.0201],
        [0.7781, 0.2861, 0.3043],
        [0.8398, 0.2941, 0.3473]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# new_* methods creates a Tensor with similar type but different size as another Tensor
x = x.new_ones(5,3,dtype=torch.double)

In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.3269, -0.6179, -1.6694],
        [ 0.4777, -1.7076, -1.2520],
        [-0.6681,  0.0839, -0.7124],
        [ 0.6443, -0.7696,  0.7994],
        [ 1.7564, -0.2901, -0.2034]])


In [9]:
# 查询Tensor size的方式
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)

In [11]:
# torch 中的三种加法
# 1.直接加
print(x+y)
# 2.torch.add
print(torch.add(x, y))
# 3.in-place add
print(y.add_(x))

tensor([[ 0.7929, -0.3522, -1.3767],
        [ 0.5334, -1.2761, -1.0927],
        [ 0.1984,  0.6713, -0.5909],
        [ 1.1114, -0.4335,  0.9478],
        [ 2.0193,  0.0761,  0.5270]])
tensor([[ 0.7929, -0.3522, -1.3767],
        [ 0.5334, -1.2761, -1.0927],
        [ 0.1984,  0.6713, -0.5909],
        [ 1.1114, -0.4335,  0.9478],
        [ 2.0193,  0.0761,  0.5270]])
tensor([[ 0.7929, -0.3522, -1.3767],
        [ 0.5334, -1.2761, -1.0927],
        [ 0.1984,  0.6713, -0.5909],
        [ 1.1114, -0.4335,  0.9478],
        [ 2.0193,  0.0761,  0.5270]])


In [12]:
# torch_add 两种返回output的方法
x = torch.rand(5,3)
y = torch.rand(5,3)
result = torch.add(x, y)
print(result)

result1 = torch.empty(5, 3)
torch.add(x, y, out=result1)
print(result1)

tensor([[1.1806, 1.9142, 1.7044],
        [1.7395, 0.8616, 1.4314],
        [0.6051, 0.9916, 1.2903],
        [1.1836, 1.6148, 1.3720],
        [1.4465, 0.7107, 1.9083]])
tensor([[1.1806, 1.9142, 1.7044],
        [1.7395, 0.8616, 1.4314],
        [0.6051, 0.9916, 1.2903],
        [1.1836, 1.6148, 1.3720],
        [1.4465, 0.7107, 1.9083]])


In [13]:
# in-place transpose Tensor.t_() 这个method里面不带argument，不会返回值
print(x)
x.t_()
print(x)

tensor([[0.4974, 0.9947, 0.7792],
        [0.9095, 0.6416, 0.4938],
        [0.2854, 0.2684, 0.8541],
        [0.8873, 0.9396, 0.4515],
        [0.9033, 0.1339, 0.9775]])
tensor([[0.4974, 0.9095, 0.2854, 0.8873, 0.9033],
        [0.9947, 0.6416, 0.2684, 0.9396, 0.1339],
        [0.7792, 0.4938, 0.8541, 0.4515, 0.9775]])


In [14]:
# 以前用的是tf.reshape，现在是reshape(Tensor.view(shape))
# x本身的尺寸没有被改变，所以需要把改变了尺寸的返回值赋给新的变量
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# 如果Tensor只有一个element，还可以用Tensor.item()的方法把它转化为一个python scalar
# 想要numpy array，可以用Tensor.numpy()
x = torch.rand(1)
print(x.item())
print(y.numpy())

0.03640854358673096
[0.77645737 0.2608863  0.95201707 0.2121417  0.9053331  0.22455418
 0.70432055 0.31426013 0.6277877  0.00821447 0.2924137  0.95873255
 0.77784634 0.8357931  0.5650422  0.6265518 ]


In [16]:
# 在pytorch中加减乘除可以自动broadcast
# 而且将设置一个变量为Tensor对应的numpy array后，将自动追踪改Tensor的变化情况，因为numpy array 和Tensor都共用一个内存位置
x = torch.rand(2,2)
y = x.numpy()
print(x+5)
print(torch.add(x, 5))
print(x.add_(5))
print(y)
x += 1
print(y)
print(x.device)

tensor([[5.4232, 5.2256],
        [5.6462, 5.5090]])
tensor([[5.4232, 5.2256],
        [5.6462, 5.5090]])
tensor([[5.4232, 5.2256],
        [5.6462, 5.5090]])
[[5.4231896 5.225643 ]
 [5.6461763 5.509046 ]]
[[6.4231896 6.225643 ]
 [6.6461763 6.509046 ]]
cpu


In [17]:
# numpy array 转化为Tensor的方法
# 与numpy array 会自动追踪Tensor一样， Tensor也会自动追踪 numpy array的数值
import numpy as np
# numpy 和 TF 一样，shape都必须添加parentheses作为形状
a = np.ones((5,3)) 
b = torch.from_numpy(a)
print(a)
np.add(a, 1, out=a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)


In [25]:
# 在TF2中，虽然Tensor也可以转化为numpy array，但是因为他们不共享内存，所以即使都在CPU上运行，互相没有影响
import tensorflow as tf
a = tf.constant([1,2,3,4])
print(a,a.device)
b = a.numpy()
b += 1
print(b)
print(a)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
[2 3 4 5]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [20]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    # 在指定device上创建Tensor
    y = torch.ones_like(x, device=device)
#     将现有的Tensor移动到指定设备， 可以同时改变他们的dtype
    print(x.device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu'), torch.double)
#     利用tensor.device可以查询他们现在位于哪个devide，注意，这不是一个method，所以不可以call， 这只是一个property
    print(z.device)
    # x现在作为存储在cuda上的Tensor，不可以用Tensor.numpy()的方法转化为numpy array，必须要先将用Tensor.cpu()的方法，
#     将它保存在内存上，再用Tensor.numpy()的方法将它转化为numpy array，所以自然没有numpy和PyTorch Tensor那种自动追踪
    tensor_cpu = x.cpu()
    print(tensor_cpu + 1)
    print(x)

cuda:0
tensor([[7.4232, 7.2256],
        [7.6462, 7.5090]], device='cuda:0')
tensor([[7.4232, 7.2256],
        [7.6462, 7.5090]]) torch.float64
cuda:0
tensor([[7.4232, 7.2256],
        [7.6462, 7.5090]])
tensor([[6.4232, 6.2256],
        [6.6462, 6.5090]], device='cuda:0')
